{% set name = "redmapper" %}
{% set version = "0.8.5.5" %}
{% set sha256 = "47777a28e2f5128499730a93ec5212fb6f4d8671702045b1be6ea934b219ce09" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/erykoff/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37 or win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - gsl
    - libblas
    - libcblas
    - numpy
  run:
    - python
    - astropy
    - matplotlib-base
    - pyyaml
    - fitsio
    - esutil
    - {{ pin_compatible('numpy') }}
    - healpy
    - scipy
    - healsparse

test:
  imports:
    - redmapper

about:
  home: https://github.com/erykoff/redmapper
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: The redMaPPer galaxy cluster finder
  description: |
    This is the python version of the red-sequence matched-filter Probabilistic
    Percolation (redMaPPer) galaxy cluster finder, originally described in
    Rykoff et al. (2014),
    (https://ui.adsabs.harvard.edu/abs/2014ApJ...785..104R/abstract).
  doc_url: https://github.com/erykoff/redmapper/tree/master/how-to
  dev_url: https://github.com/erykoff/redmapper

extra:
  recipe-maintainers:
    - erykoff
